stages:
  - build
  - deploy

variables:
  GAR_HOST: "us-central1-docker.pkg.dev"
  GAR_REPO: "spotify-repo"
  GKE_CLUSTER: "spotify-cluster"
  GKE_REGION: "us-central1"
  BACKEND_IMAGE: "$GAR_HOST/$GCP_PROJECT_ID/$GAR_REPO/backend:$CI_COMMIT_SHORT_SHA"
  FRONTEND_IMAGE: "$GAR_HOST/$GCP_PROJECT_ID/$GAR_REPO/frontend:$CI_COMMIT_SHORT_SHA"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

# ─── BUILD BACKEND ─────────────────────────────────────────
build_backend:
  stage: build
  image: google/cloud-sdk:slim
  id_tokens:
    GCP_ID_TOKEN:
      aud: https://iam.googleapis.com/projects/776180568462/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider
  services:
    - docker:27-dind
  script:
    - echo "${GCP_ID_TOKEN}" > /tmp/id_token.txt
    - |
      cat > /tmp/creds.json <<EOF
      {
        "type": "external_account",
        "audience": "//iam.googleapis.com/projects/776180568462/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider",
        "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
        "token_url": "https://sts.googleapis.com/v1/token",
        "credential_source": {
          "file": "/tmp/id_token.txt"
        },
        "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/gitlab-deployer@spotify-audio-analyzer-web-app.iam.gserviceaccount.com:generateAccessToken"
      }
      EOF
    - gcloud auth login --cred-file=/tmp/creds.json --quiet
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud auth configure-docker $GAR_HOST --quiet
    - docker build -t $BACKEND_IMAGE ./backend
    - docker push $BACKEND_IMAGE
  only:
    - main

# ─── BUILD FRONTEND ────────────────────────────────────────
build_frontend:
  stage: build
  image: google/cloud-sdk:slim
  id_tokens:
    GCP_ID_TOKEN:
      aud: https://iam.googleapis.com/projects/776180568462/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider
  services:
    - docker:27-dind
  script:
    - echo "${GCP_ID_TOKEN}" > /tmp/id_token.txt
    - |
      cat > /tmp/creds.json <<EOF
      {
        "type": "external_account",
        "audience": "//iam.googleapis.com/projects/776180568462/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider",
        "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
        "token_url": "https://sts.googleapis.com/v1/token",
        "credential_source": {
          "file": "/tmp/id_token.txt"
        },
        "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/gitlab-deployer@spotify-audio-analyzer-web-app.iam.gserviceaccount.com:generateAccessToken"
      }
      EOF
    - gcloud auth login --cred-file=/tmp/creds.json --quiet
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud auth configure-docker $GAR_HOST --quiet
    - docker build -t $FRONTEND_IMAGE ./spotify-frontend
    - docker push $FRONTEND_IMAGE
  only:
    - main

# ─── DEPLOY TO GKE ─────────────────────────────────────────
deploy_to_gke:
  stage: deploy
  image: google/cloud-sdk:slim
  id_tokens:
    GCP_ID_TOKEN:
      aud: https://iam.googleapis.com/projects/776180568462/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider
  script:
    - echo "${GCP_ID_TOKEN}" > /tmp/id_token.txt
    - |
      cat > /tmp/creds.json <<EOF
      {
        "type": "external_account",
        "audience": "//iam.googleapis.com/projects/776180568462/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider",
        "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
        "token_url": "https://sts.googleapis.com/v1/token",
        "credential_source": {
          "file": "/tmp/id_token.txt"
        },
        "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/gitlab-deployer@spotify-audio-analyzer-web-app.iam.gserviceaccount.com:generateAccessToken"
      }
      EOF
    - gcloud auth login --cred-file=/tmp/creds.json --quiet
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION
    - sed "s|IMAGE_BACKEND|$BACKEND_IMAGE|g" k8s/backend.yaml | kubectl apply -f -
    - sed "s|IMAGE_FRONTEND|$FRONTEND_IMAGE|g" k8s/frontend.yaml | kubectl apply -f -
  only:
    - main
  needs:
    - build_backend
    - build_frontend